include: package:lints/recommended.yaml

analyzer:
    exclude: [build/**]
    language:
        strict-raw-types: true
    strong-mode:
        implicit-casts: true
        implicit-dynamic: true

linter:
    rules:
        - sound-null-safety: false